name: algolia
description: >
   Algolia is a pure dart SDK, wrapped around Algolia REST API for easy implementation for your Flutter or Dart projects.
version: 1.1.2
repository: https://github.com/knoxpo/dart_algolia
homepage: https://www.algolia.com/doc/guides/building-search-ui/troubleshooting/faq/ios/#does-algolia-support-dart-and-flutter

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  meta: ^1.16.0
  http: ^1.5.0
  uuid: ^4.5.1
  universal_io: ^2.0.4

dependency_overrides:
  watcher: ^1.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.17.12
  dotenv: ^4.2.0
  #flutter_dotenv: ^6.0.0
  matcher: ^0.12.14
  characters: ^1.4.0
  material_color_utilities: ^0.11.1
